name: CI

on: [push, pull_request]

jobs:
  build:
    name: 'Build ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Env Vars'
        run: env | sort
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.802'
      - name: 'dotnet info'
        shell: pwsh
        run: dotnet --info
      - name: 'Cake build & pack'
        shell: pwsh
        run: ./build.ps1 -Target Pack
