name: CI

on: [push]

jobs:
  build:
  strategy:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402' # SDK Version to use.
    - name: Run a one-line script
      run: env | sort
