name: CI

on: [push]

jobs:
  build:
    name: 'Build ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Echo'
        if: $RUNNER_OS == 'Windows'
        run: echo 'WINDOWS'
